# Generated by Django 4.2.8 on 2025-02-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_INPC_23203', '0002_alter_cart_id_alter_cartproducts_id_alter_commune_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=10)),
                ('amount', models.FloatField()),
                ('product_type', models.CharField(max_length=50)),
            ],
        ),
    ]
