# Generated by Django 4.2.8 on 2025-02-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_INPC_23203', '0003_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='INPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20, unique=True)),
                ('value', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
